Fix commit creation
After replacing Git by Rugged I'm now performing tests on actual
repositories. The first error was:

```
TypeError: wrong argument type nil (expected Array)
bundler/gems/gisdatigo-9a5868e68638/lib/gisdatigo/git_manager.rb:33:in `create'
```

Looking at
https://github.com/libgit2/rugged/blob/master/test/commit_test.rb#L355
I've found that the only Array argument is the parents list. Thus I'm
now passing the HEAD there.