Fix commit creation
After replacing Git by Rugged I'm now performing tests on actual
repositories. This is the second error:

```
TypeError: wrong argument type nil (expected String)
bundler/gems/gisdatigo-410098d79c49/lib/gisdatigo/git_manager.rb:33:in `create'
```

By looking at
https://github.com/libgit2/rugged/blob/master/test/commit_test.rb#L419
if both message and parent options are set, the missing one is the tree.